version: '3'

networks:
  nodejs-basics:

services:

  postgres-db:
    build: ./db
    restart: always
    container_name: postgres-db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      nodejs-basics:

  nodejs-server:
    build: .
    restart: on-failure
    container_name: nodejs-server
    depends_on:
      postgres-db:
        condition: service_started
    ports:
      - ${PORT}:4000
    networks:
      nodejs-basics:
